### ISSUE TITLE
attempts to format set comprehensions fails

### ISSUE THREAD

**Issue by lsloan** [Psycojoker/PythonTidy#1]
PythonTidy was last updated before Python had set comprehensions, so it's no surprise that it fails miserably when it tries to format code that contains them.

The code I wanted to format contained this set comprehension:

``` python
{courseID for outcomeLink in courseOutcomeGroupLinks
  if outcomeLink.outcome.id == outcome.id}
```

pythontidy died with an exception that included a stack trace which ended in:

``` text
  File "/usr/bin/pythontidy", line 2554, in put
    arg.put(can_split=True)
AttributeError: SetComp instance has no attribute 'put'
```

See the offending code on [line 2554 of pythontidy](/Psycojoker/PythonTidy/blob/c28320bca90d05f7b19ca4bcd80cb2ced03e57dc/pythontidy#L2554).

**Comment by Psycojoker** [comment]
Hello,

I'm sadly not using PythonTidy myself anymore and like most of us, I've moved to autopep8 https://github.com/hhatto/autopep8 that is maintained and widely used, it should really better fit your needs.

I've attempt to write something similar using my own tools in the past but stopped as some problems were extremely complicated (and the classical "lack of free time") https://github.com/Psycojoker/pyfmt

I think that I should probably remove this repository as I have not intent in maintaining it I'm therefor closing this ticket. Don't hesitate to continue the discussion if you feel that it's appropriate.

Hope this answer could help you a bit.

Kind regards,

**Comment by sloanlance** [comment]
Yes, it is helpful. Thanks for suggesting autopep8, I'll try it. It didn't come up in my Google search for Python formatters.

You should keep this repo. It's the most useful of all available copies of PythonTidy because it's easy to install with pip. Just add notices to the repo description and README that say it's not maintained and is for historical purposes only. Also give a link to autopep8.
